TesteDextra.MVC/Models/ErrorViewModel.cs
namespace TesteDextra.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesteDextra.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TesteDextra.Application.Interfaces;
using TesteDextra.MVC.Models;

namespace TesteDextra.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPedidosApplication _pedidosApplication;

        public HomeController(IPedidosApplication pedidosApplication)
        {
            _pedidosApplication = pedidosApplication;
        }

        public IActionResult Index()
        {
            return View(_pedidosApplication.GetAllPedidos());
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesteDextra.MVC/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TesteDextra.MVC.Controllers
{
    public class PedidosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TesteDextra.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <div align="center">
            <h2>Pedidos</h2>
        </div>
    </div>
    <div class="col-md-12">
        <div align="center">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Codigo</th>
                        <th scope="col">Lanche</th>
                        <th scope="col">Complementos</th>
                        <th scope="col">Valor</th>
                        <th scope="col">Data/Hora</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @Html.Partial("_Pedidos")
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-12" align="center">
        @Html.ActionLink("Novo Pedido","Index","Pedidos", routeValues: null, htmlAttributes: new { target = "_blank", @class = "btn-block btn-sm btn-success" } )
    </div>
</div>

TesteDextra.MVC/Views/Home/_Pedidos.cshtml
@using TesteDextra.Application.ViewModel.Response
@model List<TesteDextra.Application.ViewModel.Response.PedidosViewModel>

@if (Model != null)
{
    if (Model.Any())
    {
        for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td scope="row">@(i + 1)</td>
                <td>@Model[i].Codigo</td>
                <td>@Model[i].Lanche</td>
                <td>
                    <span>@string.Join(",", Model[i].Complementos)</span>
                </td>
                <td>@Model[i].Valor</td>
                <td>@Model[i].DataHora</td>
                <td>@Model[i].Status</td>
            </tr>
        }
    }
}

TesteDextra.MVC/Views/Pedidos/Index.cshtml
<div id="divLanches">@Html.Partial("_Lanches")</div>
<div id="divComplementos">@Html.Partial("_Complementos")</div>

<script>

    $(function () {
        $("#divComplementos").hide();
    });

    function IrParaComplementos() {

        $("#divLanches").hide();
        $("#divComplementos").show();
    }

    function IrParaLanches() {
        $("#divComplementos").hide();
        $("#divLanches").show();
    }

    function CalcularPreco() {
        alert("Efetuar Calculo");
    }

</script>

TesteDextra.MVC/Views/Pedidos/_Complementos.cshtml
<div class="row">
    <div class="col-md-12">
        <div align="center">
            <h2>Novo Pedido</h2>
        </div>
    </div>
    <div class="col-md-12">
        <div align="center">
            <label>Escolha seus Complementos</label>
            <div class="form-group col-md-12">
                <div>
                    <label>Alface</label>
                    <input type="button" class="btn btn-danger btn-group-sm" style="border-radius: 45%; width: 35px" value="-" />
                    <input type="button" class="btn btn-success btn-group-sm" style="border-radius: 45%; width: 35px" value="+" />
                    <input type="text" class="input-sm" />
                    <label>$Valor</label>
                </div>

                <div>
                    <label>Tomate</label>
                    <input type="button" class="btn btn-danger btn-group-sm" style="border-radius: 45%; width: 35px" value="-" />
                    <input type="button" class="btn btn-success btn-group-sm" style="border-radius: 45%; width: 35px" value="+" />
                    <input type="text" class="input-sm" />
                    <label>$Valor</label>
                </div>

                <div>
                    <label>Carne</label>
                    <input type="button" class="btn btn-danger btn-group-sm" style="border-radius: 45%; width: 35px" value="-" />
                    <input type="button" class="btn btn-success btn-group-sm" style="border-radius: 45%; width: 35px" value="+" />
                    <input type="text" class="input-sm" />
                    <label>$Valor</label>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div align="center">
            <div class="">
                <input class="btn btn-danger btn-sm" type="button" value="Voltar" onclick="IrParaLanches()" />
                <input class="btn btn-success btn-sm" type="button" value="Proximo" onclick="CalcularPreco()" />
            </div>
        </div>
    </div>
</div>

TesteDextra.MVC/Views/Pedidos/_Lanches.cshtml
<div class="row">
    <div class="col-md-12">
        <div align="center">
            <h2>Novo Pedido</h2>
        </div>
    </div>
    <div class="col-md-12">
        <div align="center">
            <div class="form-group">
                <label for="exampleSelect2">Escolha seu Lanche</label>
                <select class="form-control" id="exampleSelect2">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div style="background-color: rgb(236, 236, 236); width: 100%; height: 20vw; margin-bottom: 10px">
            Mussum Ipsum, cacilds vidis litro abertis. Per aumento de cachacis, eu reclamis. Interagi no mé, cursus quis, vehicula ac nisi. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi.
            Mé faiz elementum girarzis, nisi eros vermeio. Leite de capivaris, leite de mula manquis sem cabeça. Pra lá , depois divoltis porris, paradis. Casamentiss faiz malandris se pirulitá.
        </div>
    </div>
    <div class="col-md-12">
        <div align="center">
            <div class="">
                <input class="btn btn-success btn-sm" type="button" value="Proximo" onclick="IrParaComplementos()" />
            </div>
        </div>
    </div>
</div>

TesteDextra.MVC/Views/Pedidos/_Step1.cshtml
<div class="row">
    <div class="col-md-12">
        <div align="center">
            <h2>Novo Pedido</h2>
        </div>
    </div>
    <div class="col-md-12">
        <div align="center">
            <div class="form-group">
                <label for="exampleSelect2">Escolha seu Lanche</label>
                <select class="form-control" id="exampleSelect2">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div style="background-color: rgb(236, 236, 236); width: 100%; height: 20vw; margin-bottom: 10px">
            Mussum Ipsum, cacilds vidis litro abertis. Per aumento de cachacis, eu reclamis. Interagi no mé, cursus quis, vehicula ac nisi. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi.
            Mé faiz elementum girarzis, nisi eros vermeio. Leite de capivaris, leite de mula manquis sem cabeça. Pra lá , depois divoltis porris, paradis. Casamentiss faiz malandris se pirulitá.
        </div>
    </div>

    <div class="col-md-12">
        <div align="center">
            <div class="">
                <input class="btn btn-success btn-sm" type="button" value="Proximo" />
            </div>
        </div>
    </div>
</div>

TesteDextra.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TesteDextra</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pedidos</a>
                <a asp-area="" asp-controller="Pedidos" asp-action="Index" class="navbar-brand">Novo Pedido</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TesteDextra</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
     
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>